// Auth ve hesap — sağlayıcı Faruk (auth, users) · KV-09 (#11)
import { z } from "zod";
import { dataOf, Empty, Id, Role, Timestamp, Url, Username, UserStatus } from "../common.ts";
import { defineEndpoint } from "../endpoint.ts";

const Email = z.email().max(254);
/** En az 10 karakter; üst sınır argon2 girdi sınırı ve DoS koruması için. */
const Password = z.string().min(10).max(128);
const Token = z.string().min(20).max(256);

/** Oturum sahibinin kendi görünümü. Sadece /me ve login cevabında döner. */
export const Me = z.strictObject({
  id: Id,
  username: Username,
  displayName: z.string().min(1).max(60),
  email: Email,
  emailVerified: z.boolean(),
  avatarUrl: Url.nullable(),
  bio: z.string().max(300).nullable(),
  status: UserStatus,
  roles: z.array(Role),
  createdAt: Timestamp,
});

const auth = { owner: "Faruk", module: "auth" } as const;
const users = { owner: "Faruk", module: "users" } as const;
const web = ["Ümit (web, KV-13)"];

export const authEndpoints = [
  defineEndpoint({
    id: "auth.register",
    domain: "auth",
    method: "POST",
    path: "/auth/register",
    summary: "Kayıt; doğrulama e-postası gönderilir",
    auth: "public",
    provider: auth,
    consumers: web,
    unblocks: ["#11", "#15"],
    availability: { status: "ready" },
    request: {
      body: z.strictObject({
        email: Email,
        username: Username,
        displayName: z.string().trim().min(1).max(60),
        password: Password,
      }),
    },
    responses: { 202: dataOf(z.strictObject({ status: z.literal("VERIFICATION_SENT") })) },
    errors: ["USERNAME_TAKEN", "FEATURE_DISABLED"],
    idempotency: "none",
    cache: "private",
    notes: [
      "E-posta zaten kayıtlıysa da aynı 202 döner (hesap varlığı sızmaz); mevcut hesaba bilgilendirme e-postası gider.",
      "Kullanıcı adı çakışması 409 USERNAME_TAKEN (kullanıcı adları zaten public).",
      "registration.enabled=false iken 503 FEATURE_DISABLED.",
    ],
  }),
  defineEndpoint({
    id: "auth.login",
    domain: "auth",
    method: "POST",
    path: "/auth/login",
    summary: "Giriş; httpOnly session cookie ayarlar",
    auth: "public",
    provider: auth,
    consumers: web,
    unblocks: ["#11", "#15", "#67"],
    availability: { status: "ready" },
    request: { body: z.strictObject({ email: Email, password: z.string().min(1).max(128) }) },
    responses: { 200: dataOf(Me) },
    errors: ["INVALID_CREDENTIALS", "ACCOUNT_RESTRICTED"],
    idempotency: "none",
    cache: "private",
    notes: [
      "Yanlış e-posta ve yanlış şifre aynı INVALID_CREDENTIALS döner.",
      "BANNED/SUSPENDED hesap 403 ACCOUNT_RESTRICTED (details.action='login').",
      "İlk başarılı girişte 20 puan bir kez verilir (#67, points.granted); paralel girişler tek grant üretir.",
    ],
  }),
  defineEndpoint({
    id: "auth.logout",
    domain: "auth",
    method: "POST",
    path: "/auth/logout",
    summary: "Mevcut oturumu iptal eder, cookie'yi siler",
    auth: "user",
    provider: auth,
    consumers: web,
    unblocks: ["#11", "#15"],
    availability: { status: "ready" },
    request: {},
    responses: { 204: Empty },
    errors: [],
    idempotency: "natural",
    cache: "private",
  }),
  defineEndpoint({
    id: "auth.email.verify",
    domain: "auth",
    method: "POST",
    path: "/auth/email/verify",
    summary: "E-posta doğrulama bağlantısındaki token'ı kullanır",
    auth: "public",
    provider: auth,
    consumers: web,
    unblocks: ["#11", "#15"],
    availability: { status: "ready" },
    request: { body: z.strictObject({ token: Token }) },
    responses: { 200: dataOf(z.strictObject({ verified: z.literal(true) })) },
    errors: ["TOKEN_INVALID_OR_EXPIRED"],
    idempotency: "natural",
    cache: "private",
    notes: ["Zaten doğrulanmış hesabın geçerli token'ı tekrar gelirse yine 200."],
  }),
  defineEndpoint({
    id: "auth.email.resend",
    domain: "auth",
    method: "POST",
    path: "/auth/email/resend",
    summary: "Doğrulama e-postasını yeniden gönderir",
    auth: "user",
    provider: auth,
    consumers: web,
    unblocks: ["#11", "#15"],
    availability: { status: "ready" },
    request: {},
    responses: { 202: Empty },
    errors: [],
    idempotency: "none",
    cache: "private",
  }),
  defineEndpoint({
    id: "auth.password.forgot",
    domain: "auth",
    method: "POST",
    path: "/auth/password/forgot",
    summary: "Şifre sıfırlama e-postası",
    auth: "public",
    provider: auth,
    consumers: web,
    unblocks: ["#11", "#15"],
    availability: { status: "ready" },
    request: { body: z.strictObject({ email: Email }) },
    responses: { 202: Empty },
    errors: [],
    idempotency: "none",
    cache: "private",
    notes: ["Hesap olsun olmasın her zaman 202 (hesap varlığı sızmaz)."],
  }),
  defineEndpoint({
    id: "auth.password.reset",
    domain: "auth",
    method: "POST",
    path: "/auth/password/reset",
    summary: "Token ile yeni şifre; bütün oturumlar iptal edilir",
    auth: "public",
    provider: auth,
    consumers: web,
    unblocks: ["#11", "#15"],
    availability: { status: "ready" },
    request: { body: z.strictObject({ token: Token, password: Password }) },
    responses: { 204: Empty },
    errors: ["TOKEN_INVALID_OR_EXPIRED"],
    idempotency: "none",
    cache: "private",
  }),
  defineEndpoint({
    id: "me.get",
    domain: "auth",
    method: "GET",
    path: "/me",
    summary: "Oturum sahibinin hesabı",
    auth: "user",
    provider: users,
    consumers: [...web, "Mehmet (profil, KV-22)"],
    unblocks: ["#11", "#15", "#24"],
    availability: { status: "ready" },
    request: {},
    responses: { 200: dataOf(Me) },
    errors: [],
    idempotency: "none",
    cache: "private",
  }),
  defineEndpoint({
    id: "me.update",
    domain: "auth",
    method: "PATCH",
    path: "/me",
    summary: "Görünen ad, biyografi, avatar",
    auth: "user",
    provider: users,
    consumers: [...web, "Mehmet (profil, KV-22)"],
    unblocks: ["#11", "#24"],
    availability: { status: "ready" },
    request: {
      body: z
        .strictObject({
          displayName: z.string().trim().min(1).max(60).optional(),
          bio: z.string().trim().max(300).nullable().optional(),
          avatarMediaId: Id.nullable().optional(),
        })
        .refine((b) => Object.keys(b).length > 0, "En az bir alan gönderilmeli"),
    },
    responses: { 200: dataOf(Me) },
    errors: ["MEDIA_NOT_USABLE"],
    idempotency: "natural",
    cache: "private",
    notes: ["avatarMediaId kullanıcının kendi AVATAR amaçlı, REJECTED olmayan görseli olmalı; APPROVED olana kadar avatarUrl null döner."],
  }),
];
