// Profil, kaydetme, takip, karar güncellemesi, ilgi alanı, paylaşım, duyuru, puan — sağlayıcı Mehmet
// KV-15 (#17), KV-22 (#24), KV-23 (#25), KV-25 (#27), KV-42 (#44), #67 (puan)
import { z } from "zod";
import { CommentView } from "./comments.ts";
import { PollCard } from "./polls.ts";
import { Count, CursorQuery, dataOf, Id, IdParams, pageOf, PublicUser, Timestamp, Url, Username } from "../common.ts";
import { defineEndpoint } from "../endpoint.ts";

export const PublicProfile = z.strictObject({
  ...PublicUser.shape,
  bio: z.string().nullable(),
  joinedAt: Timestamp,
  stats: z.strictObject({ pollCount: Count, votesReceived: Count, commentCount: Count }),
});

export const DecisionUpdate = z.strictObject({
  pollId: Id,
  chosenOptionId: Id.nullable(),
  note: z.string(),
  updatedAt: Timestamp,
});

export const DecisionState = z.strictObject({ decision: DecisionUpdate.nullable(), following: z.boolean(), isAuthor: z.boolean() });

export const Announcement = z.strictObject({
  id: Id,
  title: z.string(),
  body: z.string(),
  level: z.enum(["INFO", "WARNING"]),
  startsAt: Timestamp,
  endsAt: Timestamp.nullable(),
});

export const LedgerReason = z.enum(["INITIAL_GRANT", "PUBLISH", "ADMIN_ADJUSTMENT", "MODERATION_REFUND"]);
export const LedgerEntry = z.strictObject({
  id: Id,
  delta: z.number().int().refine((n) => n !== 0),
  balanceAfter: Count,
  reason: LedgerReason,
  referenceId: Id.nullable(),
  createdAt: Timestamp,
});
export const PointsSummary = z.strictObject({ balance: Count, publishCost: z.number().int().min(0) });

const UsernameParams = z.strictObject({ username: Username });
const growth = (module: string) => ({ owner: "Mehmet", module }) as const;
const web = ["Ümit (web)"];

export const growthEndpoints = [
  defineEndpoint({
    id: "profiles.get",
    domain: "growth",
    method: "GET",
    path: "/profiles/:username",
    summary: "Herkese açık profil",
    auth: "public",
    provider: growth("profiles"),
    consumers: web,
    unblocks: ["#24"],
    availability: { status: "ready" },
    request: { params: UsernameParams },
    responses: { 200: dataOf(PublicProfile) },
    errors: [],
    idempotency: "none",
    cache: "public",
  }),
  defineEndpoint({
    id: "profiles.polls",
    domain: "growth",
    method: "GET",
    path: "/profiles/:username/polls",
    summary: "Kullanıcının gönderileri",
    auth: "public",
    provider: growth("profiles"),
    consumers: web,
    unblocks: ["#24"],
    availability: { status: "ready" },
    request: { params: UsernameParams, query: CursorQuery },
    responses: { 200: pageOf(PollCard) },
    errors: ["INVALID_CURSOR"],
    idempotency: "none",
    cache: "viewer",
  }),
  defineEndpoint({
    id: "profiles.comments",
    domain: "growth",
    method: "GET",
    path: "/profiles/:username/comments",
    summary: "Kullanıcının yorumları",
    auth: "public",
    provider: growth("profiles"),
    consumers: web,
    unblocks: ["#24"],
    availability: { status: "ready" },
    request: { params: UsernameParams, query: CursorQuery },
    responses: { 200: pageOf(CommentView) },
    errors: ["INVALID_CURSOR"],
    idempotency: "none",
    cache: "viewer",
  }),
  defineEndpoint({
    id: "bookmarks.put",
    domain: "growth",
    method: "PUT",
    path: "/polls/:id/bookmark",
    summary: "Kaydet",
    auth: "user",
    provider: growth("bookmarks"),
    consumers: web,
    unblocks: ["#24"],
    availability: { status: "ready" },
    request: { params: IdParams },
    responses: { 200: dataOf(z.strictObject({ saved: z.literal(true) })) },
    errors: [],
    idempotency: "natural",
    cache: "private",
  }),
  defineEndpoint({
    id: "bookmarks.delete",
    domain: "growth",
    method: "DELETE",
    path: "/polls/:id/bookmark",
    summary: "Kaydı kaldır",
    auth: "user",
    provider: growth("bookmarks"),
    consumers: web,
    unblocks: ["#24"],
    availability: { status: "ready" },
    request: { params: IdParams },
    responses: { 200: dataOf(z.strictObject({ saved: z.literal(false) })) },
    errors: [],
    idempotency: "natural",
    cache: "private",
  }),
  defineEndpoint({
    id: "bookmarks.list",
    domain: "growth",
    method: "GET",
    path: "/me/bookmarks",
    summary: "Kaydedilenler (sadece sahibi)",
    auth: "user",
    provider: growth("bookmarks"),
    consumers: web,
    unblocks: ["#24"],
    availability: { status: "ready" },
    request: { query: CursorQuery },
    responses: { 200: pageOf(PollCard) },
    errors: ["INVALID_CURSOR"],
    idempotency: "none",
    cache: "private",
  }),
  defineEndpoint({
    id: "follows.put",
    domain: "growth",
    method: "PUT",
    path: "/polls/:id/follow",
    summary: "Sonucu takip et",
    auth: "user",
    provider: growth("decision-updates"),
    consumers: web,
    unblocks: ["#25"],
    availability: { status: "ready" },
    request: { params: IdParams },
    responses: { 200: dataOf(z.strictObject({ following: z.literal(true) })) },
    errors: [],
    idempotency: "natural",
    cache: "private",
  }),
  defineEndpoint({
    id: "follows.delete",
    domain: "growth",
    method: "DELETE",
    path: "/polls/:id/follow",
    summary: "Takibi bırak",
    auth: "user",
    provider: growth("decision-updates"),
    consumers: web,
    unblocks: ["#25"],
    availability: { status: "ready" },
    request: { params: IdParams },
    responses: { 200: dataOf(z.strictObject({ following: z.literal(false) })) },
    errors: [],
    idempotency: "natural",
    cache: "private",
  }),
  defineEndpoint({
    id: "decisions.get", domain: "growth", method: "GET", path: "/polls/:id/decision",
    summary: "Karar ve takip durumu", auth: "public", provider: growth("decision-updates"), consumers: web,
    unblocks: ["#25"], availability: { status: "ready" }, request: { params: IdParams },
    responses: { 200: dataOf(DecisionState) }, errors: [], idempotency: "none", cache: "viewer",
  }),
  defineEndpoint({
    id: "decisions.put",
    domain: "growth",
    method: "PUT",
    path: "/polls/:id/decision",
    summary: "Kararımı verdim (sahibin seçimi ve gerekçesi)",
    auth: "owner",
    provider: growth("decision-updates"),
    consumers: web,
    unblocks: ["#25"],
    availability: { status: "ready" },
    request: {
      params: IdParams,
      body: z.strictObject({ chosenOptionId: Id.nullable(), note: z.string().trim().min(1).max(1000) }),
    },
    responses: { 200: dataOf(DecisionUpdate) },
    errors: ["CONTENT_LOCKED"],
    idempotency: "natural",
    cache: "private",
    notes: ["chosenOptionId aynı anketin seçeneği olmalı (bileşik FK); tartışmada null."],
  }),
  defineEndpoint({
    id: "interests.get",
    domain: "growth",
    method: "GET",
    path: "/me/interests",
    summary: "Seçili ilgi kategorileri",
    auth: "user",
    provider: growth("onboarding"),
    consumers: web,
    unblocks: ["#17"],
    availability: { status: "ready" },
    request: {},
    responses: { 200: dataOf(z.strictObject({ categoryIds: z.array(Id) })) },
    errors: [],
    idempotency: "none",
    cache: "private",
  }),
  defineEndpoint({
    id: "interests.put",
    domain: "growth",
    method: "PUT",
    path: "/me/interests",
    summary: "İlgi kategorilerini ayarla (tam liste)",
    auth: "user",
    provider: growth("onboarding"),
    consumers: web,
    unblocks: ["#17", "#29"],
    availability: { status: "ready" },
    request: { body: z.strictObject({ categoryIds: z.array(Id).min(1).max(20) }) },
    responses: { 200: dataOf(z.strictObject({ categoryIds: z.array(Id) })) },
    errors: [],
    idempotency: "natural",
    cache: "private",
  }),
  defineEndpoint({
    id: "shares.create",
    domain: "growth",
    method: "POST",
    path: "/polls/:id/shares",
    summary: "Kaynak ölçümlü paylaşım bağlantısı",
    auth: "public",
    provider: growth("share"),
    consumers: web,
    unblocks: ["#27"],
    availability: { status: "ready" },
    request: { params: IdParams, body: z.strictObject({ channel: z.enum(["x", "whatsapp", "copy", "other"]) }) },
    responses: { 201: dataOf(z.strictObject({ shareId: z.string(), url: Url })) },
    errors: [],
    idempotency: "none",
    cache: "private",
    notes: ["Paylaşım kartı (OG görseli) gizli sonuçta yüzde/toplam oy içermez."],
  }),
  defineEndpoint({
    id: "announcements.active",
    domain: "growth",
    method: "GET",
    path: "/announcements/active",
    summary: "Şu an gösterilecek duyurular",
    auth: "public",
    provider: growth("announcements"),
    consumers: web,
    unblocks: ["#44"],
    availability: { status: "ready" },
    request: {},
    responses: { 200: dataOf(z.array(Announcement)) },
    errors: [],
    idempotency: "none",
    cache: "public",
  }),
  defineEndpoint({
    id: "points.get",
    domain: "growth",
    method: "GET",
    path: "/me/points",
    summary: "Yayın puanı bakiyesi ve yayın maliyeti",
    auth: "user",
    provider: growth("points"),
    consumers: web,
    unblocks: ["#67", "#15"],
    availability: { status: "planned", tableIn: "#67" },
    request: {},
    responses: { 200: dataOf(PointsSummary) },
    errors: [],
    idempotency: "none",
    cache: "private",
  }),
  defineEndpoint({
    id: "points.ledger",
    domain: "growth",
    method: "GET",
    path: "/me/points/ledger",
    summary: "Puan hareketleri (append-only)",
    auth: "user",
    provider: growth("points"),
    consumers: web,
    unblocks: ["#67"],
    availability: { status: "planned", tableIn: "#67" },
    request: { query: CursorQuery },
    responses: { 200: pageOf(LedgerEntry) },
    errors: ["INVALID_CURSOR"],
    idempotency: "none",
    cache: "private",
  }),
];
