// Bildirimler — sağlayıcı Utku · KV-21 (#23), KV-34 (#36); tüketici Mehmet KV-35 (#37)
import { z } from "zod";
import { Count, CursorQuery, dataOf, Id, pageOf, PublicUser, Timestamp } from "../common.ts";
import { defineEndpoint } from "../endpoint.ts";

export const NotificationType = z.enum([
  "COMMENT_ON_POLL",
  "REPLY_TO_COMMENT",
  "ALTERNATIVE_ON_POLL",
  "POLL_MILESTONE",
  "POLL_TRENDING",
  "POLL_CLOSED",
  "DECISION_UPDATED",
  "MODERATION_APPLIED",
  "COMMUNITY_FEATURED",
]);

export const NotificationView = z.strictObject({
  id: Id,
  type: NotificationType,
  subject: z.strictObject({ type: z.enum(["POLL", "COMMENT", "COMMUNITY", "USER"]), id: Id }),
  actor: PublicUser.nullable(),
  /** Tipe göre küçük özet alanlar (ör. milestone: 100). Oy seçimi veya özel veri içermez. */
  data: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()])),
  readAt: Timestamp.nullable(),
  createdAt: Timestamp,
});

export const NotificationPreferences = z.strictObject({
  // Gönderilmeyen tip varsayılan (açık) kabul edilir.
  types: z.partialRecord(NotificationType, z.boolean()),
});

const notifications = { owner: "Utku", module: "notifications" } as const;
const center = ["Mehmet (bildirim merkezi, KV-35)"];
const PollParams = z.strictObject({ pollId: Id });

export const notificationEndpoints = [
  defineEndpoint({
    id: "notifications.list",
    domain: "notifications",
    method: "GET",
    path: "/notifications",
    summary: "Bildirimler (yeniden eskiye)",
    auth: "user",
    provider: notifications,
    consumers: center,
    unblocks: ["#23", "#37"],
    availability: { status: "ready" },
    request: { query: z.strictObject({ ...CursorQuery.shape, unreadOnly: z.stringbool().default(false) }) },
    responses: { 200: pageOf(NotificationView) },
    errors: ["INVALID_CURSOR"],
    idempotency: "none",
    cache: "private",
  }),
  defineEndpoint({
    id: "notifications.unreadCount",
    domain: "notifications",
    method: "GET",
    path: "/notifications/unread-count",
    summary: "Okunmamış sayısı (rozet)",
    auth: "user",
    provider: notifications,
    consumers: [...center, "Ümit (app shell)"],
    unblocks: ["#23", "#37"],
    availability: { status: "ready" },
    request: {},
    responses: { 200: dataOf(z.strictObject({ count: Count })) },
    errors: [],
    idempotency: "none",
    cache: "private",
  }),
  defineEndpoint({
    id: "notifications.markRead",
    domain: "notifications",
    method: "POST",
    path: "/notifications/read",
    summary: "Okundu işaretle (seçili veya hepsi)",
    auth: "user",
    provider: notifications,
    consumers: center,
    unblocks: ["#23", "#37"],
    availability: { status: "ready" },
    request: {
      body: z.union([
        z.strictObject({ ids: z.array(Id).min(1).max(100) }),
        z.strictObject({ all: z.literal(true) }),
      ]),
    },
    responses: { 200: dataOf(z.strictObject({ updated: Count })) },
    errors: [],
    idempotency: "natural",
    cache: "private",
  }),
  defineEndpoint({
    id: "notifications.preferences.get",
    domain: "notifications",
    method: "GET",
    path: "/notifications/preferences",
    summary: "Bildirim tercihleri",
    auth: "user",
    provider: notifications,
    consumers: center,
    unblocks: ["#36", "#37"],
    availability: { status: "ready" },
    request: {},
    responses: { 200: dataOf(NotificationPreferences) },
    errors: [],
    idempotency: "none",
    cache: "private",
  }),
  defineEndpoint({
    id: "notifications.preferences.update",
    domain: "notifications",
    method: "PATCH",
    path: "/notifications/preferences",
    summary: "Tip bazında aç/kapat",
    auth: "user",
    provider: notifications,
    consumers: center,
    unblocks: ["#36", "#37"],
    availability: { status: "ready" },
    request: { body: z.strictObject({ types: z.partialRecord(NotificationType, z.boolean()) }) },
    responses: { 200: dataOf(NotificationPreferences) },
    errors: [],
    idempotency: "natural",
    cache: "private",
    notes: ["MODERATION_APPLIED kapatılamaz; gönderilirse 400 VALIDATION_ERROR."],
  }),
  defineEndpoint({
    id: "notifications.mutes.put",
    domain: "notifications",
    method: "PUT",
    path: "/notifications/mutes/:pollId",
    summary: "Bir anketin bildirimlerini sessize al",
    auth: "user",
    provider: notifications,
    consumers: center,
    unblocks: ["#36"],
    availability: { status: "ready" },
    request: { params: PollParams },
    responses: { 200: dataOf(z.strictObject({ muted: z.literal(true) })) },
    errors: [],
    idempotency: "natural",
    cache: "private",
  }),
  defineEndpoint({
    id: "notifications.mutes.delete",
    domain: "notifications",
    method: "DELETE",
    path: "/notifications/mutes/:pollId",
    summary: "Sessizi kaldır",
    auth: "user",
    provider: notifications,
    consumers: center,
    unblocks: ["#36"],
    availability: { status: "ready" },
    request: { params: PollParams },
    responses: { 200: dataOf(z.strictObject({ muted: z.literal(false) })) },
    errors: [],
    idempotency: "natural",
    cache: "private",
  }),
];
