import { test,expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
test("real auth HTTP: registration, fragment verification, cookie reload, reset and logout",async({page,request})=>{
  const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
  page.on("requestfailed",request=>console.log("Failed request:",request.url(),request.failure()?.errorText));
  await page.goto("/kayit");
  await expect(page.locator(".demo-note,.demo-banner,.demo-controls")).toHaveCount(0);
  await page.getByLabel("Görünen ad",{exact:true}).fill("Ümit Test");
  await page.getByLabel("Kullanıcı adı",{exact:true}).fill("umit_browser");
  await page.getByLabel("E-posta",{exact:true}).fill("umit.browser@example.test");
  await page.getByLabel("Şifre",{exact:true}).fill("Browser-password-123");
  await page.getByRole("button",{name:"Hesap oluştur",exact:true}).click();
  await expect(page.getByRole("status").filter({hasText:"E-postanı kontrol et"})).toBeVisible();
  const mail=await (await request.get("http://127.0.0.1:4011/__test__/mail")).json();
  const token=mail.text.match(/#token=([A-Za-z0-9_-]+)/)[1];
  await page.goto(`/dogrula#token=${token}`);
  await expect(page).toHaveURL(/\/dogrula$/);
  await page.getByRole("button",{name:"E-postayı doğrula",exact:true}).click();
  await expect(page.getByText("E-postan doğrulandı.",{exact:false})).toBeVisible();
  await page.goto("/giris");
  await page.getByLabel("E-posta",{exact:true}).fill("umit.browser@example.test");
  await page.getByLabel("Şifre",{exact:true}).fill("Browser-password-123");
  await page.getByRole("button",{name:"Giriş yap",exact:true}).click();
  await expect(page.getByRole("button",{name:"Çıkış",exact:true})).toBeVisible();
  const cookies=await page.context().cookies();expect(cookies.find(c=>c.name==="kv_session")?.httpOnly).toBe(true);
  await page.goto("/hesap");await page.reload();
  await expect(page.getByRole("heading",{name:"Merhaba, Ümit Test."})).toBeVisible();
  expect(await page.evaluate(()=>Object.keys(localStorage))).toEqual([]);
  await expect(page.locator(".balance")).toHaveCount(0);
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
  await page.goto("/sifremi-unuttum");
  await page.getByLabel("E-posta",{exact:true}).fill("umit.browser@example.test");
  await page.getByRole("button",{name:"Sıfırlama isteği oluştur"}).click();
  await expect(page.getByText("Bu hesap varsa sıfırlama bağlantısı gönderildi.")).toBeVisible();
  const resetMail=await (await request.get("http://127.0.0.1:4011/__test__/mail")).json();
  await page.goto(`/sifre-yenile#token=${resetMail.text.match(/#token=([A-Za-z0-9_-]+)/)[1]}`);
  await page.getByLabel("Şifre",{exact:true}).fill("Changed-password-123");
  await page.getByRole("button",{name:"Şifreyi yenile",exact:true}).click();
  await expect(page.getByRole("button",{name:"Çıkış",exact:true})).toHaveCount(0);
  await page.goto("/giris");
  await page.getByLabel("E-posta",{exact:true}).fill("umit.browser@example.test");
  await page.getByLabel("Şifre",{exact:true}).fill("Changed-password-123");
  await page.getByRole("button",{name:"Giriş yap",exact:true}).click();
  await page.getByRole("button",{name:"Çıkış",exact:true}).click();
  await page.goto("/hesap");await expect(page.getByRole("heading",{name:"Hesabınla katıl."})).toBeVisible();
  expect(errors).toEqual([]);
});
