import { test,expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
test("real auth HTTP: registration, fragment verification, cookie reload, reset and logout",async({page,request})=>{
  const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
  page.on("requestfailed",request=>console.log("Failed request:",request.url(),request.failure()?.errorText));
  await page.goto("/kayit");
  await expect(page.locator(".demo-note,.demo-banner,.demo-controls")).toHaveCount(0);
  await page.getByLabel("Görünen ad",{exact:true}).fill("Ümit Test");
  await page.getByLabel("Kullanıcı adı",{exact:true}).fill("umit_browser");
  await page.getByLabel("E-posta",{exact:true}).fill("umit.browser@example.test");
  await page.getByLabel("Şifre",{exact:true}).fill("Browser-password-123");
  await page.getByRole("button",{name:"Hesap oluştur",exact:true}).click();
  await expect(page.getByRole("button",{name:"Çıkış",exact:true})).toBeVisible();
  await expect(page.locator(".balance")).toContainText("20");
  const mail=await (await request.get("http://127.0.0.1:4011/__test__/mail")).json();
  const token=mail.text.match(/#token=([A-Za-z0-9_-]+)/)[1];
  await page.goto(`/dogrula#token=${token}`);
  await expect(page).toHaveURL(/\/dogrula$/);
  await page.getByRole("button",{name:"E-postayı doğrula",exact:true}).click();
  await expect(page.getByText("E-postan doğrulandı.",{exact:false})).toBeVisible();
  await page.goto("/giris");
  await page.getByLabel("E-posta",{exact:true}).fill("umit.browser@example.test");
  await page.getByLabel("Şifre",{exact:true}).fill("Browser-password-123");
  await page.getByRole("button",{name:"Giriş yap",exact:true}).click();
  await expect(page.getByRole("button",{name:"Çıkış",exact:true})).toBeVisible();
  const cookies=await page.context().cookies();expect(cookies.find(c=>c.name==="kv_session")?.httpOnly).toBe(true);
  await page.goto("/hesap");await page.reload();
  await expect(page.getByRole("heading",{name:"Ümit Test",exact:true})).toBeVisible();
  await expect(page.getByRole("heading",{name:"Kaydedilenler",exact:true})).toBeVisible();
  // This server mounts auth only; unavailable profile/bookmark routes must not look empty.
  await expect(page.getByRole("button",{name:"Kaydedilenleri tekrar yükle"})).toBeVisible();
  await expect(page.locator("main").getByRole("alert")).toBeVisible();
  await expect(page.getByText("Henüz bir gönderi kaydetmedin.",{exact:true})).toHaveCount(0);
  expect(await page.evaluate(()=>Object.keys(localStorage))).toEqual([]);
  await expect(page.locator(".balance")).toContainText("20");
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
  await page.goto("/sifremi-unuttum");
  await page.getByLabel("E-posta",{exact:true}).fill("umit.browser@example.test");
  await page.getByRole("button",{name:"Sıfırlama isteği oluştur"}).click();
  await expect(page.getByText("Bu hesap varsa sıfırlama bağlantısı gönderildi.")).toBeVisible();
  const resetMail=await (await request.get("http://127.0.0.1:4011/__test__/mail")).json();
  await page.goto(`/sifre-yenile#token=${resetMail.text.match(/#token=([A-Za-z0-9_-]+)/)[1]}`);
  await page.getByLabel("Şifre",{exact:true}).fill("Changed-password-123");
  await page.getByRole("button",{name:"Şifreyi yenile",exact:true}).click();
  await expect(page.getByRole("button",{name:"Çıkış",exact:true})).toHaveCount(0);
  await page.goto("/giris");
  await page.getByLabel("E-posta",{exact:true}).fill("umit.browser@example.test");
  await page.getByLabel("Şifre",{exact:true}).fill("Changed-password-123");
  await page.getByRole("button",{name:"Giriş yap",exact:true}).click();
  await page.getByRole("button",{name:"Çıkış",exact:true}).click();
  await page.goto("/hesap");await expect(page.getByRole("heading",{name:"Hesabınla katıl."})).toBeVisible();
  expect(errors).toEqual([]);
});

test("duplicate registration cannot claim success or replace the existing password", async ({page}) => {
  const id = `dup_${Date.now().toString(36)}`;
  const email = `${id}@example.test`;
  const original = "Original-browser-password-123";
  await page.goto("/kayit");
  await page.getByLabel("Görünen ad",{exact:true}).fill("Duplicate Test");
  await page.getByLabel("Kullanıcı adı",{exact:true}).fill(id);
  await page.getByLabel("E-posta",{exact:true}).fill(email);
  await page.getByLabel("Şifre",{exact:true}).fill(original);
  await page.getByRole("button",{name:"Hesap oluştur",exact:true}).click();
  await expect(page.getByRole("button",{name:"Çıkış",exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Çıkış",exact:true}).click();
  await page.goto("/kayit");
  await page.getByLabel("Görünen ad",{exact:true}).fill("Duplicate Test");
  await page.getByLabel("Kullanıcı adı",{exact:true}).fill(`${id}_new`);
  await page.getByLabel("E-posta",{exact:true}).fill(email);
  await page.getByLabel("Şifre",{exact:true}).fill("Replacement-browser-password-123");
  await page.getByRole("button",{name:"Hesap oluştur",exact:true}).click();
  await expect(page.locator("main").getByRole("alert").filter({hasText:"Yeniden kayıt mevcut şifreni değiştirmez"})).toBeVisible();
  await expect(page.getByLabel("Şifre",{exact:true})).toHaveValue("");
  await expect(page.getByRole("button",{name:"Çıkış",exact:true})).toHaveCount(0);
  await expect(page.getByRole("link",{name:"Şifremi unuttum",exact:true})).toHaveAttribute("href",new RegExp(encodeURIComponent(email)));
  await page.getByRole("link",{name:"Mevcut hesabımla giriş yap",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Tekrar hoş geldin.",exact:true})).toBeVisible();
  await expect(page.getByLabel("E-posta",{exact:true})).toHaveValue(email);
  await page.getByLabel("Şifre",{exact:true}).fill(original);
  await page.getByRole("button",{name:"Giriş yap",exact:true}).click();
  await expect(page.getByRole("button",{name:"Çıkış",exact:true})).toBeVisible();
  await expect(page.locator(".balance")).toContainText("20");
});
